name: Docker Build Test

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t actions-lab-test .

      - name: Run container
        run: |
          docker run --rm actions-lab-test
